spring.application.name=slotsecure-backend

spring.datasource.url=jdbc:mysql://localhost:3306/slotsecure_db
spring.datasource.username=root
spring.datasource.password=jaijothi2004@5678
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=your-256-bit-secret-key-here-make-it-long-and-random-for-security
jwt.expiration=86400000